runtime: python3.8
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

# [START handlers]
handlers:
- url: /static
  static_dir: static
  - url: /.*
    script: run.app
# [END handlers]
